"""Pydantic models for the player registry.

These models are used during Cricsheet data ingestion to parse, validate and
resolve player records before they are written to the ``players`` table.
"""

from __future__ import annotations

import re
from datetime import date

from pydantic import BaseModel, Field, field_validator


class RawPeopleRecord(BaseModel):
    """A single row from Cricsheet's ``people.csv`` file.

    The CSV has the columns::

        identifier,name,unique_name,key_cricinfo,key_cricinfo_profile,
        key_cricbuzz,key_cricbuzz_profile,key_cricsheet

    Only ``identifier`` and ``name`` are required; all others are optional.
    """

    identifier: str = Field(..., description="Cricsheet unique identifier")
    name: str = Field(..., description="Full display name")
    unique_name: str | None = Field(default=None, description="Disambiguated name")
    key_cricinfo: str | None = Field(default=None)
    key_cricinfo_profile: str | None = Field(default=None)
    key_cricbuzz: str | None = Field(default=None)
    key_cricbuzz_profile: str | None = Field(default=None)
    key_cricsheet: str | None = Field(default=None)

    @field_validator("identifier")
    @classmethod
    def identifier_not_empty(cls, v: str) -> str:
        """Ensure identifier is non-empty after stripping whitespace."""
        stripped = v.strip()
        if not stripped:
            raise ValueError("identifier must not be empty")
        return stripped

    @field_validator("name")
    @classmethod
    def name_not_empty(cls, v: str) -> str:
        """Ensure name is non-empty after stripping whitespace."""
        stripped = v.strip()
        if not stripped:
            raise ValueError("name must not be empty")
        return stripped


class ResolvedPlayer(BaseModel):
    """A fully-resolved player record ready for database insertion.

    Combines data from Cricsheet's people.csv with any manual overrides.
    """

    player_id: str = Field(..., description="Canonical slug (e.g. virat-kohli-ind)")
    name: str = Field(..., description="Canonical display name")
    country: str | None = Field(default=None, description="ISO country code or name")
    role: str | None = Field(
        default=None,
        description="batsman / bowler / allrounder / wicketkeeper",
    )
    dob: date | None = Field(default=None, description="Date of birth")
    aliases: list[str] = Field(
        default_factory=list,
        description="Known alternative spellings or abbreviations",
    )
    cricinfo_id: str | None = Field(default=None)
    cricbuzz_id: str | None = Field(default=None)
    cricsheet_id: str | None = Field(default=None)

    @field_validator("player_id")
    @classmethod
    def player_id_slug(cls, v: str) -> str:
        """Validate that player_id is a lowercase slug."""
        if not re.match(r"^[a-z0-9\-]+$", v):
            raise ValueError(
                f"player_id must be a lowercase hyphen-slug, got: {v!r}"
            )
        return v

    @field_validator("role")
    @classmethod
    def role_valid(cls, v: str | None) -> str | None:
        """Validate role against known values."""
        allowed = {None, "batsman", "bowler", "allrounder", "wicketkeeper"}
        if v not in allowed:
            raise ValueError(
                f"role must be one of {allowed - {None}!r}, got: {v!r}"
            )
        return v

    @classmethod
    def from_raw(
        cls,
        raw: RawPeopleRecord,
        *,
        country: str | None = None,
        role: str | None = None,
        dob: date | None = None,
    ) -> "ResolvedPlayer":
        """Build a :class:`ResolvedPlayer` from a :class:`RawPeopleRecord`.

        The ``player_id`` is generated by slugifying the identifier.
        """
        slug = raw.identifier.lower().replace(" ", "-").replace("_", "-")
        aliases: list[str] = []
        if raw.unique_name and raw.unique_name != raw.name:
            aliases.append(raw.unique_name)
        return cls(
            player_id=slug,
            name=raw.name,
            country=country,
            role=role,
            dob=dob,
            aliases=aliases,
            cricinfo_id=raw.key_cricinfo,
            cricbuzz_id=raw.key_cricbuzz,
            cricsheet_id=raw.key_cricsheet,
        )


class PlayerOverride(BaseModel):
    """A manual alias → player_id mapping from ``player_overrides.json``.

    Used to handle common name variations that cannot be resolved
    automatically from Cricsheet data.
    """

    alias: str = Field(
        ..., description="Normalised lowercased alias to match against"
    )
    player_id: str = Field(
        ..., description="Canonical player_id this alias resolves to"
    )
    reason: str | None = Field(
        default=None, description="Human-readable justification"
    )

    @field_validator("alias")
    @classmethod
    def alias_lowercase(cls, v: str) -> str:
        """Force alias to lowercase."""
        return v.strip().lower()

    @field_validator("player_id")
    @classmethod
    def player_id_slug(cls, v: str) -> str:
        """Validate that player_id is a lowercase slug."""
        if not re.match(r"^[a-z0-9\-]+$", v):
            raise ValueError(
                f"player_id must be a lowercase hyphen-slug, got: {v!r}"
            )
        return v
